apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  namespace: microservices
spec:
  storageClassName: nfsstorage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20G
