using command --from-literal=key=value

image: nginx
env:
- name: configmap
  valueFrom:
  configMapKeyRef:
    name: cmd
    key: a
------
using directory --from-literal=filepath

containers:
 - name: httpd
   image: nginx
   imagePullPolicy: IfNotPresent
   ports:
     - containerPort: 80
   volumeMounts:
   - name: configmap
     mountpath: /opt/volume
volumes:
  - name: configmap
    configMap:
      name: directory


     
