apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jenkins
spec:
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [Jenkins]}
      - {key: abc, operator: NotIn, values: [test]}
  template:
    metadata:
      labels:
        app: Jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      nodeSelector:
        name: master
