apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd
spec:
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [httpd]}
      - {key: abc, operator: NotIn, values: [test]}
  template:
    metadata:
      labels:
        app: httpd
    spec: 
      containers:
        - name: httpd
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
