apiVersion: v1
kind: Pod
metadata:
  name: containers
  labels:
    env: test
spec:
  containers:
  - name: nginx1
    image: nginx
    ports: 
      - containerPort: 80
    imagePullPolicy: IfNotPresent
  - name: sonar
    image: sonarqube
    ports: 
      - containerPort: 9000
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    env: test
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
      - containerPort: 80
    imagePullPolicy: IfNotPresent
