apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: sonar
spec:
  containers:
  - image: sonarqube
    name: sonarqube
    imagePullPolicy: IfNotPresent
    ports: 
      - containerPort: 9000
        
