apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [sonar]}
      - {key: env, operator: NotIn, values: [prod]}
  template:
    metadata:
      labels:
        app: sonar
        env: test
    spec:
      containers:
      - image: sonarqube
        name: sonar
        ports: 
          - containerPort: 9000
        
